apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - artifactory-jcr
  - chart-repository
  - config-maps
  - git-events/sync.yaml
  - git-repositories
  - helm-repositories
  - ingress-nginx
  - ingresses
  - keycloak
  - kustomizations
  - policies
  - projects
  - services
  - teams
