apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - artifactory-jcr/sync.yaml
  - artifactory-oci/sync.yaml
  - chart-repository
  - config-maps
  - crds
  - git-event-listener
  - git-events/sync.yaml
  - git-repositories
  - helm-repositories
  - ingress-nginx
  - ingresses
  - keycloak
  - kustomizations
  - nats
  - policies
  - projects
  - providers
  - services
  - sops-age
  - teams
  - tenant-resources/sync.yaml
