apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: git-event-listener
  namespace: ${ENVIRONMENT}
spec:
  type: nats
  address: nats://nats.${ENVIRONMENT}.svc.cluster.local:4222
  channel: flux.gitrepository.events
