apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: git-event-listener
  namespace: ${ENVIRONMENT}
spec:
  type: generic
  address: http://git-event-listener.${ENVIRONMENT}.svc.cluster.local:8080/events
