apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-oss
  namespace: ${ENVIRONMENT}
spec:
  interval: 10m
  timeout: 10m
  dependsOn:
    - name: chart-repository
      namespace: ${ENVIRONMENT}
    - name: artifactory-jcr
      namespace: ${ENVIRONMENT}
  chart:
    spec:
      chart: artifactory-oss
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: chart-repository
  values:
    replicaCount: 1
    cleanup:
      image:
        repository: ${ARTIFACTORY_JCR_HOST}/docker-local/org.nguiland.infra/alpine-ops-toolkit
      envMap:
        ART_OSS_URL: ${ARTIFACTORY_OSS_SCHEME}://${ARTIFACTORY_OSS_HOST}:${ARTIFACTORY_OSS_PORT}/artifactory
