apiVersion: cicd.nguiland.io/v1alpha1
kind: DependencyGraph
metadata:
  name: nguiland
  namespace: ${ENVIRONMENT}
spec:
  project: nguiland
  repositories:
    - name: dependencies
    - name: docker
    - name: dto
      dependencies:
        - dependencies
    - name: helm
    - name: io-utils
      dependencies:
        - dependencies
    - name: ms-parent
      dependencies:
        - dependencies
    - name: orm
      dependencies:
        - dependencies
    - name: rest
      dependencies:
        - dependencies
        - orm
        - dto
    - name: web-oauth2
      dependencies:
        - dependencies
