apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: artifactory-oci
  namespace: ${ENVIRONMENT}
spec:
  type: oci
  url: oci://${IMAGE_REGISTRY_HOST}/docker-local
  interval: 5m
  secretRef:
    name: docker-config
