apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chart-repository
  namespace: ${ENVIRONMENT}
spec:
  interval: 10m
  chart:
    spec:
      chart: ./core/chart-repository
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: nguiland-ops-helm
      interval: 10m
  values:
    replicaCount: 1
