apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nguiland-ops-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: develop
  secretRef:
    name: flux-system
  url: https://github.com/biya-bi/nguiland-ops-secrets.git
