apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-install
  namespace: ${ENVIRONMENT}
spec:
  interval: 10m
  dependsOn:
    - name: sops-age
  path: ./install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: nguiland-ops-tekton
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env-settings
