apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dependency-graphs.yaml
  - git-repositories.yaml
  - helm-releases.yaml
  - streams.yaml
  - tekton-cicd.yaml
  - tekton-install.yaml
