apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: optional-streams
  namespace: ${ENVIRONMENT}
spec:
  interval: 10m
  timeout: 10m
  dependsOn:
    - name: nats
  path: ./common/optional/streams
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: jetstream.nats.io/v1beta2
      kind: Stream
      name: flux-gitrepository-events
      namespace: ${ENVIRONMENT}
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env-settings
