apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: ssh-credentials
spec:
  tenantSelector:
    matchLabels:
      platform.nguiland.org/ssh-credentials: "true"

  resyncPeriod: 10m

  resources:
    - namespacedItems:
        - apiVersion: v1
          kind: Secret
          name: ssh-credentials
          namespace: ${ENVIRONMENT}
