apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-pipelinerun-cleanup
  namespace: ${ENVIRONMENT}
spec:
  interval: 10m
  dependsOn:
    - name: artifactory-jcr
      namespace: ${ENVIRONMENT}
  chart:
    spec:
      chart: org.nguiland.infra/tekton-pipelinerun-cleanup
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: artifactory-oci
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
