apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: docker-build
  namespace: ${ENVIRONMENT}
spec:
  providerRef:
    name: docker-build
  inclusionList:
    - "^stored artifact for commit '.*'$"
  eventSeverity: info
  eventMetadata:
    contextDir: .
    pipeline: docker-build
  eventSources:
    - kind: GitRepository
      name: docker
