apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: docker-build
  namespace: ${ENVIRONMENT}
spec:
  providerRef:
    name: docker-build
  inclusionList:
    - "^stored artifact for commit '.*'$"
  eventSeverity: info
  eventMetadata:
    contextDir: .
    pipelineName: docker-build
    eventListenerUrl: http://el-docker-build.${ENVIRONMENT}.svc.cluster.local:8080/
  eventSources:
    - kind: GitRepository
      name: docker
