apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-chart-oci-publish
  namespace: ${ENVIRONMENT}
spec:
  providerRef:
    name: helm-chart-oci-publish
  inclusionList:
    - "^stored artifact for commit '.*'$"
  eventSeverity: info
  eventMetadata:
    chartsDir: addons
    excludedCharts: cronjob-common
    registry: oci://${ARTIFACTORY_JCR_HOST}:${ARTIFACTORY_JCR_PORT}/docker-local
    pipelineName: helm-chart-oci-publish
    eventListenerUrl: http://el-helm-chart-oci-publish.${ENVIRONMENT}.svc.cluster.local:8080/
  eventSources:
    - kind: GitRepository
      name: helm
