apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-chart-oci-publish
  namespace: ${ENVIRONMENT}
spec:
  providerRef:
    name: helm-chart-oci-publish
  inclusionList:
    - "^stored artifact for commit '.*'$"
  eventSeverity: info
  eventMetadata:
    chartsDir: addons
    excludedCharts: cronjob-common
    registry: oci://${ARTIFACTORY_JCR_HOST}:${ARTIFACTORY_JCR_PORT}/docker-local
    pipeline: helm-chart-oci-publish
  eventSources:
    - kind: GitRepository
      name: helm
