apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: maven-lib
  namespace: ${ENVIRONMENT}
spec:
  providerRef:
    name: maven-lib
  inclusionList:
    - "^stored artifact for commit '.*'$"
  eventSeverity: info
  eventMetadata:
    contextDir: .
    pipeline: maven-lib
  eventSources:
    - kind: GitRepository
      name: io-utils
    - kind: GitRepository
      name: dependencies
    - kind: GitRepository
      name: web-oauth2
    - kind: GitRepository
      name: ms-parent
    - kind: GitRepository
      name: rest
    - kind: GitRepository
      name: orm
    - kind: GitRepository
      name: dto
