apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: git-event-listener
  namespace: ${ENVIRONMENT}
spec:
  interval: 10m
  timeout: 10m
  dependsOn:
    - name: teams-namespaces
    - name: git-events
  path: ./common/base/git-event-listener
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env-settings
