apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../optional

patches:
  - patch: |-
      - op: remove
        path: /spec/tls
    target:
      kind: Ingress
      name: nguiland
  - patch: |-
      - op: add
        path: /spec/rules/-
        value:
          host: host.docker.internal
          http:
            paths:
              - backend:
                  service:
                    name: artifactory-jcr
                    port:
                      number: 8082
                path: /
                pathType: Prefix
    target:
      kind: Ingress
      name: nguiland
  - patch: |-
      - op: replace
        path: /spec/path
        value: ./common/overlays/local/artifactory-oci
    target:
      kind: Kustomization
      name: artifactory-oci
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: ${ENVIRONMENT}
    target:
      kind: HelmRelease
      name: artifactory-jcr
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: ${ENVIRONMENT}
    target:
      kind: HelmRelease
      name: artifactory-oss
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: ${ENVIRONMENT}
    target:
      kind: HelmRelease
      name: keycloak
