apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../optional

patches:
  - patch: |-
      - op: remove
        path: /spec/tls
    target:
      kind: Ingress
      name: nguiland
  - patch: |-
      - op: add
        path: /spec/rules/-
        value:
          host: host.docker.internal
          http:
            paths:
              - backend:
                  service:
                    name: artifactory-jcr
                    port:
                      number: 8082
                path: /
                pathType: Prefix
    target:
      kind: Ingress
      name: nguiland
  - patch: |-
      - op: add
        path: /spec/insecure
        # We are on a cluster on our local development machine, so we can allow insecure connections to the registry,
        # which is assumed to be local as well. We shouldn't have to worry about certificates in this case, and this
        # allows us to avoid the complexity of setting up a local certificate authority and issuing certificates for
        # our local registry. In upper environments, we will have a valid certificate for the registry, so this patch
        # have not been included in other overlays.
        value: true
    target:
      kind: HelmRepository
      name: artifactory-oci
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: ${ENVIRONMENT}
    target:
      kind: HelmRelease
      name: artifactory-jcr
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: ${ENVIRONMENT}
    target:
      kind: HelmRelease
      name: artifactory-oss
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: ${ENVIRONMENT}
    target:
      kind: HelmRelease
      name: keycloak
